### ISSUE TITLE
skip_prompt param not work for mirror command

### ISSUE THREAD

**Issue by azhurbilo** [rgs1/zk_shell#100]
I want to run `mirror` command in crontab (none-interactive) but even with `--run-once` it's waiting for prompt (yes/no)

**Comment by rgs1** [comment]
@azhurbilo the mirror command supports the `skip_prompt` parameter, if that's set to true you won't get a prompt:

https://github.com/rgs1/zk_shell/blob/master/zk_shell/shell.py#L597
