### ISSUE TITLE
Readonly doesn't work?

### ISSUE THREAD

**Issue by unixrh** [rgs1/zk_shell#106]
It works fine by all other commands, but with --readonly, I can still rm nodes.

Is it a bug or I didn't get the right way using readonly?

**Comment by rgs1** [comment]
@unixrh it has to be supported server-side... After connection, run the `session_info` command and you'll get a `state=CONNECTED_RO` line if you got read-only support.  If not, you'll just get `state=CONNECTED`.

**Comment by rgs1** [comment]
We could however make it more obvious that `--readonly` is best effort, and that it really is up to the server. Or, we could make the connection fail when you ask for `--readonly` but you don't get it.

**Comment by unixrh** [comment]
Thanks for the information, now I've found the crux of this problem. 
I was thinking that zk-shell would help to block the modify-operations from the client-side.
