### ISSUE TITLE
ZOOKEEPER SERVER WARN: EndOfStreamException: Unable to read additional data from client, it probably closed the socket

### ISSUE THREAD

**Issue by rab4u** [rgs1/zk_shell#113]
**CMD** : zk-shell "$ZOO_SERVERS" --run-once 'mirror / json://!zookeeper-backup.json/'
**Description** : The above command executes successfully but after the execution Zookeeper server is throwing End of stream exception. it seems that zk-shell is closing the connection abruptly 
**Exception info**:
 2020-10-16 13:37:42,606 [myid:2] - WARN  [NIOWorkerThread-1:NIOServerCnxn@364] - Unexpected exception
zoo2                   | EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /192.168.48.6:51942, session = 0x20022c059cb000a
zoo2                   |        at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
zoo2                   |        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
zoo2                   |        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
zoo2                   |        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
zoo2                   |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
zoo2                   |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
zoo2                   |        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by rgs1** [comment]
@rab4u I think we should explicitly close the sessions here:

https://github.com/rgs1/zk_shell/blob/master/zk_shell/copy_util.py#L185

mind sending a patch?

**Comment by rgs1** [comment]
Closing for now, happy to review a PR tho.
