### ISSUE TITLE
Does zk_shell supports sequential nodes copy maintaining correct sequence number?

### ISSUE THREAD

**Issue by NotAndD** [rgs1/zk_shell#114]
As the title suggest, I'm trying to understand if it is possible to mirror from one cluster to another but maintaining correct sequence numbers of all znodes mirrored so that the next sequential node created would get the correct number.

**Comment by rgs1** [comment]
Sequential znodes depend on a counter in the parent, see:

```
(CONNECTED [zookeeper:2181]) /test> create foo ''
(CONNECTED [zookeeper:2181]) /test> cd foo
(CONNECTED [zookeeper:2181]) /test/foo> create bar '' false true
(CONNECTED [zookeeper:2181]) /test/foo> create bar '' false true
(CONNECTED [zookeeper:2181]) /test/foo> ls
bar0000000000
bar0000000001
(CONNECTED [zookeeper:2181]) /test/foo> rm bar0000000000
(CONNECTED [zookeeper:2181]) /test/foo> rm bar0000000001
(CONNECTED [zookeeper:2181]) /test/foo> create bar '' false true
(CONNECTED [zookeeper:2181]) /test/foo> ls
bar0000000002
```

So if there's a "hole" in your list of sequential znodes, you won't be able to recreate it unless you also recreate the hole... (we could implement this though). ZooKeeper doesn't provide a direct api to manipulate the sequential counter in the parent node, so the only way of setting the sequential counter to the right point is by creating/deleting/creating the znodes until you get to that state.

**Comment by NotAndD** [comment]
I see, thank you for the info! Recreating the hole doesn't sound like an easy process if ZK has no api to manipulate it.. even if I made something to create, delete and then create again znodes for the right amount of times, I would still need to do this operation for each single znode I need to mirror, if I understood correctly?

With no api exposing this number manipulation, looks like the most easy way to mirror the znodes is something like backup and then recovery of the snapshots or something similar to that.

**Comment by rgs1** [comment]
> I see, thank you for the info! Recreating the hole doesn't sound like an easy process if ZK has no api to manipulate it.. even if I made something to create, delete and then create again znodes for the right amount of times, I would still need to do this operation for each single znode I need to mirror, if I understood correctly?

Correct. 

]
