### ISSUE TITLE
Allow Editing of Nodes

### ISSUE THREAD

**Issue by ubiquitousthey** [rgs1/zk_shell#22]
It would be great if I could use my $EDITOR to edit node content.

**Comment by rgs1** [comment]
Ah yes - that would be useful. How about something like:

```shell
(CONNECTED) /> edit path/to/foo
```

If $EDITOR is set, launch $EDITOR with the znode's content. Upon saving, prompt the user to confirm if the update. I guess we could compare if the content changed or not, but sometimes you might want to reset a node with the same content (i.e.: to force a watch to fire). Maybe say so in the confirmation message.

If $EDITOR is not set, an alternate method would be to set it via something like:

```shell
(CONNECTED) /> conf set editor emacs
```

So, if $EDITOR is not set we can fall back to the internal conf variable `editor`. If that's not there, we'd display edit's help.

A full example (given $EDITOR set to emacs):
```shell
(CONNECTED) /> get path/to/foo
bar
(CONNECTED) /> edit path/to/foo
# emacs opens up with content 'bar'
# update to 'new bar'
# save
Update? [y/n]:
y
(CONNECTED) /> get path/to/foo
new bar
```

Thoughts?

**Comment by ubiquitousthey** [comment]
That is exactly what I was thinking.  This is much like how you use an editor in psql, chef/knife, git, etc.  I think they basically , pull some content into a temp file, allow editing, and then compare it to the source before updating.

We are starting to use zookeeper for storing more configuration data, and this would be very helpful.  I probably don't have time for a PR for the feature, but let me know if I can help with testing or something else.

**Comment by ubiquitousthey** [comment]
I think if I was doing it, I probably wouldn't ask for a confirmation and leave that up to what happens in the editor if you can do the compare between the current value and the temporary file.

**Comment by rgs1** [comment]
@ubiquitousthey : what do you think of that PR? An example here:

https://asciinema.org/a/18531

**Comment by ubiquitousthey** [comment]
Very cool!  That will make my life much easier.  Thanks.

**Comment by rgs1** [comment]
@ubiquitousthey : pushed, i'll do a release later today so you can get the change via pip.

**Comment by rgs1** [comment]
Done:

https://github.com/rgs1/zk_shell/commit/c07bcd8141cba1cc8145c6c01e4cd92d54941801

and

https://twitter.com/pypi_updates/status/586203419767136256
