### ISSUE TITLE
Dependencies question

### ISSUE THREAD

**Issue by gl101** [rgs1/zk_shell#31]
Out of the dependencies listed
ansicolors
kazoo>=2.0
nose
tabulate

Can you say which are needed only for testing and which are needed for zkshell itself?

Thanks

**Comment by rgs1** [comment]
nose is only for testing, all the others are needed at regular runtime as declared in setup.py:

```
      install_requires=['ansicolors', 'kazoo>=2.0', 'tabulate'],
      tests_require=['ansicolors', 'kazoo>=2.0', 'nose', 'tabulate'],
      extras_require={
          'test': ['ansicolors', 'kazoo>=2.0', 'nose', 'tabulate'],
      },
```

**Comment by gl101** [comment]
thanks
