### ISSUE TITLE
Add verbose mode

### ISSUE THREAD

**Issue by harlowja** [rgs1/zk_shell#39]
It'd be nice if there was a verbose mode that showed the commands in kazoo being executed (be neat to see exactly what runs/is sent to zookeeper for each corresponding `zk_shell` command somehow).

**Comment by rgs1** [comment]
this should probably be achievable via logging.basicConfig(level=logging.debug) or such..

**Comment by rgs1** [comment]
i.e. we should expose --log-level flag that would trigger logging.basicConfig

**Comment by harlowja** [comment]
Sure, that might just be fine :)
