### ISSUE TITLE
sessions in chkzk is -1

### ISSUE THREAD

**Issue by ghost** [rgs1/zk_shell#62]
I am seeing -1 for 'sessions' row of chkzk
I assume this should be the number of client connections?

This is consistent, against many clusters. As it happens they are all running 3.4.6

Client runs on Python version 2.7.6 on Ubuntu 14.04
zkshell 1.0.06 and also 1.1.1

**Comment by gl101** [comment]
So looking at the code for chkzk, the sessions row should hold the value of "zk_global_sessions". 
Haven't run into this from an mntr command and I can't seem to find it in the zookeeper source in 3.4/3.5 or trunk branches.
