### ISSUE TITLE
`dump --help` makes zk-shell quit

### ISSUE THREAD

**Issue by objmagic** [rgs1/zk_shell#80]
I am using zk-shell of version 1.0.04 on CentOS 7 machine. When I connected to the host and entered `dump --help`, zk-shell printed out the help message and quit itself. Is this expected behavior?

**Comment by rgs1** [comment]
@objmagic definitely not expected; it's because argparse doesn't handle well optional params (i.e.: `--something`) when it's expecting a positional argument (i.e.: `<something>`). Trying to thing of an elegant way of handling this... (that doesn't require `except SystemExit`).

**Comment by rgs1** [comment]
Fixed in xcmd here: https://github.com/rgs1/xcmd/pull/3

**Comment by rgs1** [comment]
@objmagic i've just published a new release -- 1.1.3 -- which should fix this, lmk how it goes. Thanks!
