### ISSUE TITLE
zk_shell crash in python 3.7, async it's a reserved keyword

### ISSUE THREAD

**Issue by yriveiro** [rgs1/zk_shell#90]
I'm trying to run zk-shell in python3.7 and I'm hitting this error:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/zk-shell", line 13, in <module>
    from zk_shell.cli import CLI
  File "/usr/local/lib/python3.7/site-packages/zk_shell/cli.py", line 128
    async = False if params.sync_connect or not interactive else True
          ^
SyntaxError: invalid syntax
```

I think is related to the fact that in python 3.7 async is a reserved keyword.

**Comment by rgs1** [comment]
@yriveiro thanks for reporting! Mind submitting a PR for this?

**Comment by yriveiro** [comment]
@rgs1, I'm rewriting all async variables to is_async but I'm stuck with this line:

`src = Proxy.from_string(params.src, True, params.async, params.verbose)`

This `params` variable is external, therefore if I change it to is_async I will break a ton of user code.

This change is not backwards compatible with user code written in versions below 3.7

The documentation should be updated to reflect this change.

Thoughts?

**Comment by rgs1** [comment]
I think it's fine to break Params interface, I don't think there's that
much code relying on it. Thanks!
